# first phase starts
title: Ranvir Singh's first site
description: Greatest website of all times
# first phase ends
# second phase starts
dribble: ranvir
email: ranvir.singh1114@gmail.com
facebook: 
flickr: 
github: 
instagram: 
linkedin: 
pinterest: 
rss: 
twitter: 
stackoverflow: 
youtube: 
googleplus: 
disqus: 
google_analytics: 
# second phase ends
# third phase starts
theme: minima
# third phase ends
