# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Product')),
                ('item_name', models.CharField(max_length=200)),
                ('profit_percent', models.IntegerField(default=5)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('base.product',),
        ),
    ]
