# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_time', models.IntegerField()),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('request_data', models.CharField(max_length=5000)),
                ('response_data', models.CharField(max_length=5000)),
                ('status_code', models.IntegerField()),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
