# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='price_paid',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.Customer'),
        ),
    ]
