# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[(b'VEGETABLE', b'VEGETABLE'), (b'FRUIT', b'FRUIT')], default=b'VEGETABLE', max_length=200)),
                ('quantity_type', models.CharField(choices=[(b'DOZEN', b'DOZEN'), (b'KILOGRAM', b'KILOGRAM')], default=b'KILOGRAM', max_length=200)),
            ],
        ),
    ]
