# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('VEGETABLE', 'VEGETABLE'), ('FRUIT', 'FRUIT')], default='VEGETABLE', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('DOZEN', 'DOZEN'), ('KILOGRAM', 'KILOGRAM')], default='KILOGRAM', max_length=200),
        ),
    ]
