# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180725_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
