# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 18:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('layout', models.CharField(blank=True, choices=[('post', 'post'), ('page', 'page')], max_length=100, null=True)),
                ('title', models.CharField(max_length=2000)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theJekyllProject.Post')),
            ],
        ),
    ]
