# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('theJekyllProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Your site name', max_length=200)),
                ('description', models.CharField(default='Description of the site', max_length=2000)),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteExclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SitePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocialProfile',
            fields=[
                ('site_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='theJekyllProject.SiteData')),
                ('dribble', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('flickr', models.CharField(blank=True, max_length=200, null=True)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=200, null=True)),
                ('rss', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('stackoverflow', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('googleplus', models.CharField(blank=True, max_length=200, null=True)),
                ('disqus', models.CharField(blank=True, max_length=200, null=True)),
                ('google_analytics', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('site_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='theJekyllProject.SiteData')),
                ('theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='siteplugin',
            name='site_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theJekyllProject.SiteData'),
        ),
        migrations.AddField(
            model_name='siteexclude',
            name='site_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theJekyllProject.SiteData'),
        ),
    ]
