# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0002_repomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepoModel',
            new_name='Repo',
        ),
    ]
