# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theJekyllProject', '0002_auto_20171002_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesocialprofile',
            name='site_data',
        ),
        migrations.AddField(
            model_name='sitesocialprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
