# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theJekyllProject', '0003_auto_20171003_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteexclude',
            name='site_data',
        ),
        migrations.RemoveField(
            model_name='siteplugin',
            name='site_data',
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='site_data',
        ),
        migrations.AddField(
            model_name='siteexclude',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteplugin',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
