# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0004_repo_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='user',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='repo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='theJekyllProject.Repo'),
            preserve_default=False,
        ),
    ]
