# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0004_auto_20171004_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesocialprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
