# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0005_auto_20171024_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesocialprofile',
            old_name='dribble',
            new_name='dribbble',
        ),
    ]
