# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0005_auto_20171005_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='name',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='title',
            field=models.CharField(default='Your site title', max_length=200),
        ),
    ]
