# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0006_auto_20171025_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='user',
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='repo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='theJekyllProject.Repo'),
            preserve_default=False,
        ),
    ]
