# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0011_auto_20171219_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteexclude',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteplugin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sitesocialprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='siteexclude',
            name='repo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theJekyllProject.Repo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteplugin',
            name='repo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theJekyllProject.Repo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesocialprofile',
            name='repo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='theJekyllProject.Repo'),
            preserve_default=False,
        ),
    ]
