# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0012_auto_20180212_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
