# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0013_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
