# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0014_page_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theJekyllProject.Repo')),
            ],
        ),
    ]
