# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0016_auto_20180309_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='Description of the Page', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='repo',
            name='template',
            field=models.CharField(choices=[(b'NS', 'TEMPLATE NOT SET'), (b'JN', 'JEKYLL NOW'), (b'SB', b'STARTBOOTSTRAP')], default=b'NS', max_length=2),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='author',
            field=models.CharField(blank=True, default='Author of the site', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='baseurl',
            field=models.CharField(blank=True, default='/jekyllblog', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='url',
            field=models.CharField(blank=True, default='http://blog.jeklog.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
