# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theJekyllProject', '0017_auto_20180507_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='template',
            field=models.CharField(choices=[('NS', 'TEMPLATE NOT SET'), ('JN', 'JEKYLL NOW'), ('SB', 'STARTBOOTSTRAP')], default='NS', max_length=2),
        ),
    ]
